language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.3.8
- 2.4.5
- 2.5.3
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-rocket-chat.gemspec
- gem install sensu-plugins-rocket-chat-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: xtDjnuvPoI8lDfO5tzX7yq7vISEe73tR+nseUr06stfWUGD3NDOc1/S11M7i62m7f3l2z91T3oumIYPLoaBs//WZpeAzO9wQQBlyvwriLEdVAN3oCpJBqyMMjnYa7SptNp8MKLmwY0oEuonPI54UK5uaxRDoiM6zBhcO7xEDxlnFP+VIXC6P7G4kdvAibwwKTU6R9OjXWOJwV/lhgUjrnHy+iMIWk5szIQOXmV9kOOepoZULnCon/I6Vn7T1005cJLyrOayCUcRJkuGlvvV6gHrmhamO1xlVEt02JFa1tLBKH5BHO0/dAo4B81mcP+5G5+3E8hNrWI8YFS69LPl5qLxa74ouh19ku0iX6d80TDwfJ6Wyz5XfP4z0+GisBcZ/AUIiPJERGlxldENdzAEG15HRVp31f4RHVSWaB4zZfHUocGJF3yOKU/Hly+0nD+P06wjIn0LG5/WaOwAiPBEx1UUNYU7dp9gjVCo1Xsji5Jtlbo7MG9aRxxBbcckFU1zGqWbT6N5rhnRUK1Uy9XsfzdIbTnHmWAQ/5j8b94k0pbTUBUXKk5U0XRr1e8/13nFbt8H3HyOvED2jLs2KMrMwBMtiB9vkKVt1o+3j/0hAkdfn40IdtF5aZlYI/oVhj+heSnRNc2by4y2Ls9jSEVRiJ13EhUO92MRoEoJXhecPRAc=
  gem: sensu-plugins-rocket-chat
  on:
    tags: true
    all_branches: true
    rvm: 2.5.3
    repo: sensu-plugins/sensu-plugins-rocket-chat
